app:
  name: server-app
  image: kubeapp 
  tag: :latest
  endpoint: /ping/
  endpointDev: /ping/
  pullPolicy: IfNotPresent
  apiPort: 8000
  resources:
    limits:
      cpu: '1'
      memory: 900Mi
    requests:
      cpu: '0.5'
      memory: 500Mi
  replicas: 1
  readiness:
    initialDelaySeconds: 3 
    periodSeconds: 3
    timeoutSeconds: 3
    failureThreshold: 2
